name: Trivy Scan For OpenMetadata Ingestion Docker Image

on:
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch:
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
          docker-images: false

      - name: Checkout Repository
        uses: actions/checkout@v4
            
      - name: Prepare for Docker Build
        id: prepare
        uses: ./.github/actions/prepare-for-docker-build
        with:
          image: openmetadata-ingestion
          tag: trivy
          is_ingestion: true


      - name: Build Docker Image
        run: |
          docker build -t openmetadata-ingestion:trivy -f ingestion/Dockerfile.ci .


      - name: Run Trivy Image Scan
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: "image"
          image-ref: openmetadata-ingestion:trivy
          hide-progress: false
          ignore-unfixed: true
          severity: "HIGH,CRITICAL"
          skip-dirs: "/opt/airflow/dags,/home/airflow/ingestion/pipelines"
          scan-ref: .
          format: 'template'
          template: "@.github/trivy/templates/github.tpl"
          output: "trivy-results-ingestion.md"
        env:
          TRIVY_DISABLE_VEX_NOTICE: "true"
    
      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy-results-ingestion.md ]]; then
            cat trivy-results-ingestion.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No vulnerabilities found." >> $GITHUB_STEP_SUMMARY
          fi
